development:
  adapter: postgresql
  encoding: utf8
  database: flashcards_development
  username: postgres
  password: qwerty
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: flashcards_test
  username: postgres
  password: qwerty
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: flashcards_production
  username: postgres
  password: qwerty
  host: localhost
