#!/usr/bin/env bash
LNG=$(xkblayout-state print %s | awk '{print toupper($0)}')
case $LNG in
  "US")
    CLR=\#66CCFF ;; # green
  "RU")
    CLR=\#FFCCFF ;; # red
  *)
    CLR=\#FFFFFF ;; # all others default-white
esac
echo "$LNG"
echo "$LNG"
echo "$CLR"
